WebPortal_BAK/WebPortal/Controllers/Corporate/BusinessLocationMapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPortal.GeneralClass;
using WebPortal.Model;

namespace WebPortal.Controllers.Corporate
{
    public class BusinessLocationMapController : Controller
    {
        //
        // GET: /BusinessLocationMap/
        FrInternallEntities db = new FrInternallEntities();

        public ActionResult Index()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.ToList();

            return View(listMenuContent);
        }
    }
}

WebPortal_BAK/WebPortal/Controllers/Corporate/BusinessPlantationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPortal.GeneralClass;
using WebPortal.Model;

namespace WebPortal.Controllers.Corporate
{
    public class BusinessPlantationController : Controller
    {
        //
        // GET: /BusinessPlantation/
        FrInternallEntities db = new FrInternallEntities();

        public ActionResult Index()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "Plantation").ToList();

            return View(listMenuContent);
        }

        [SessionTimeout]
        [HttpGet]
        public ActionResult EditBusinessPlantation()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "Plantation").ToList();
            listMenuContent.First().MenuContent = listMenuContent.First().MenuContent.Replace(";", System.Environment.NewLine);

            return View(listMenuContent);
        }

        [SessionTimeout]
        [HttpPost]
        public ActionResult EditBusinessPlantation(T_MsMenuContent content)
        {
            T_MsMenuContent menuContent = (from n in db.T_MsMenuContent
                                           where n.Menu == content.Menu
                                           select n).First();
            menuContent.MenuContent = content.MenuContent.Replace(System.Environment.NewLine, ";");
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

WebPortal_BAK/WebPortal/Controllers/Corporate/BusinessProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPortal.GeneralClass;
using WebPortal.Model;

namespace WebPortal.Controllers.Corporate
{
    public class BusinessProductController : Controller
    {
        //
        // GET: /BusinessProduct/
        FrInternallEntities db = new FrInternallEntities();

        public ActionResult Index()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "Product").ToList();

            return View(listMenuContent);
        }

        [SessionTimeout]
        [HttpGet]
        public ActionResult EditBusinessProduct()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "Product").ToList();
            listMenuContent.First().MenuContent = listMenuContent.First().MenuContent.Replace(";", System.Environment.NewLine);

            return View(listMenuContent);
        }

        [SessionTimeout]
        [HttpPost]
        public ActionResult EditBusinessProduct(T_MsMenuContent content)
        {
            T_MsMenuContent menuContent = (from n in db.T_MsMenuContent
                                           where n.Menu == content.Menu
                                           select n).First();
            menuContent.MenuContent = content.MenuContent.Replace(System.Environment.NewLine, ";");
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

WebPortal_BAK/WebPortal/Controllers/Corporate/BusinessRefineryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPortal.GeneralClass;
using WebPortal.Model;

namespace WebPortal.Controllers.Corporate
{
    public class BusinessRefineryController : Controller
    {
        //
        // GET: /BusinessRefinery/
        FrInternallEntities db = new FrInternallEntities();

        public ActionResult Index()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "Refinery").ToList();

            return View(listMenuContent);
        }

        [SessionTimeout]
        [HttpGet]
        public ActionResult EditBusinessRefinery()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "Refinery").ToList();
            listMenuContent.First().MenuContent = listMenuContent.First().MenuContent.Replace(";", System.Environment.NewLine);

            return View(listMenuContent);
        }

        [SessionTimeout]
        [HttpPost]
        public ActionResult EditBusinessRefinery(T_MsMenuContent content)
        {
            T_MsMenuContent menuContent = (from n in db.T_MsMenuContent
                                           where n.Menu == content.Menu
                                           select n).First();
            menuContent.MenuContent = content.MenuContent.Replace(System.Environment.NewLine, ";");
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

WebPortal_BAK/WebPortal/Controllers/Corporate/CorporateProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPortal.GeneralClass;
using WebPortal.Model;

namespace WebPortal.Controllers.Corporate
{
    public class CorporateProfileController : Controller
    {
        //
        // GET: /CorporateProfile/
        FrInternallEntities db = new FrInternallEntities();

        public ActionResult Index()
        {
            //MsMenuContent masterMenuContent = new MsMenuContent();
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "Corporate Profile").ToList();

            return View(listMenuContent);
        }

        [SessionTimeout]
        [HttpGet]
        public ActionResult EditCorporateProfile()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "Corporate Profile").ToList();
            listMenuContent.First().MenuContent = listMenuContent.First().MenuContent.Replace(";", System.Environment.NewLine);

            return View(listMenuContent);

        }

        [SessionTimeout]
        [HttpPost]
        public ActionResult EditCorporateProfile(T_MsMenuContent content)
        {
            T_MsMenuContent menuContent = (from n in db.T_MsMenuContent
                                           where n.Menu == content.Menu
                                           select n).First();
            menuContent.MenuContent = content.MenuContent.Replace(System.Environment.NewLine, ";");

            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

WebPortal_BAK/WebPortal/Controllers/Corporate/HistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPortal.GeneralClass;
using WebPortal.Model;

namespace WebPortal.Controllers.Corporate
{
    public class HistoryController : Controller
    {
        //
        // GET: /History/
        FrInternallEntities db = new FrInternallEntities();

        public ActionResult Index()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "History").ToList();

            return View(listMenuContent);
        }

        [SessionTimeout]
        [HttpGet]
        public ActionResult EditHistory()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "History").ToList();
            listMenuContent.First().MenuContent = listMenuContent.First().MenuContent.Replace(";", System.Environment.NewLine);

            return View(listMenuContent);
        }

        [SessionTimeout]
        [HttpPost]
        public ActionResult EditHistory(T_MsMenuContent content)
        {
            T_MsMenuContent menuContent = (from n in db.T_MsMenuContent
                                           where n.Menu == content.Menu
                                           select n).First();
            menuContent.MenuContent = content.MenuContent.Replace(System.Environment.NewLine, ";");
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

WebPortal_BAK/WebPortal/Controllers/Corporate/VisionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPortal.GeneralClass;
using WebPortal.Model;

namespace WebPortal.Controllers.Corporate
{
    public class VisionController : Controller
    {
        //
        // GET: /VMV/
        FrInternallEntities db = new FrInternallEntities();

        public ActionResult Index()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "Vision Mision And Values").ToList();

            return View(listMenuContent);
        }

        [SessionTimeout]
        [HttpGet]
        public ActionResult EditVision()
        {
            List<T_MsMenuContent> listMenuContent = db.T_MsMenuContent.Where(model => model.Menu == "Vision Mision And Values").ToList();
            listMenuContent.First().MenuContent = listMenuContent.First().MenuContent.Replace(";", System.Environment.NewLine);

            return View(listMenuContent);
        }

        [SessionTimeout]
        [HttpPost]
        public ActionResult EditVision(T_MsMenuContent content)
        {
            T_MsMenuContent menuContent = (from n in db.T_MsMenuContent
                                           where n.Menu == content.Menu
                                           select n).First();
            menuContent.MenuContent = content.MenuContent.Replace(System.Environment.NewLine, ";");
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

WebPortal_BAK/WebPortal/Views/Corporate/Vision/EditVision.cshtml
@model List<WebPortal.Model.T_MsMenuContent>
@{
    ViewBag.Title = "Web Portal | Edit Vision";
}

<div id="wrapper">
    <section id="inner-headline">
        <div class="container">
            <div class="row">
                <div class="span5">
                    <div class="inner-heading">
                        <h2>Edit Vision</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="content">
        <div class="container">
            <div class="row">
                <div class="span12">
                    @using (Html.BeginForm("EditVision", "Vision", FormMethod.Post, new { @class = "contactForm", @enctype = "multipart/form-data" }))
                    {
                    <div class="span12 margintop10 form-group">
                        @Html.TextAreaFor(model => model.FirstOrDefault().MenuContent, new { @class = "input-block-level", @rows = 12, @style = "resize:none;"})
                        @Html.HiddenFor(model => model.FirstOrDefault().Menu, new {@id = "Menu" })
                        <p class="text-center">
                            <button class="btn btn-large btn-theme margintop10" type="submit">Edit Vision</button>
                        </p>
                    </div>
                    }
                </div>
            </div>
        </div>
    </section>
</div>

WebPortal_BAK/WebPortal/Views/Corporate/Vision/Index.cshtml
@model List<WebPortal.Model.T_MsMenuContent>
@{
    ViewBag.Title = "Web Portal | Vision Mision And Values";
}


<body>
    <div id="wrapper">
        <section id="featured">
            <!-- start slider -->
            <!-- Slider -->
            <div id="nivo-slider">
                <div class="nivo-slider">
                    <img src="~/Design/images/Vision.jpg" alt="" title="#caption-1" />
                </div>
            </div>
            <!-- end slider -->
        </section>
        <section id="content">
            <div class="container">
                <div class="row">
                    <div class="span10">
                        @foreach (var content in Model)
                        {
                            foreach (string contentsplit in content.MenuContent.ToString().Split(';'))
                            {
                                if (contentsplit != "")
                                {
                                    <p>
                                        @if (contentsplit.Contains("@h@"))
                                        {
                                            <strong>@contentsplit.Replace("@h@", "")</strong>
                                        }
                                        else
                                        {
                                            if (contentsplit == "")
                                            {
                                            @contentsplit <br />
                                            }
                                            else
                                            {
                                            @contentsplit
                                            }
                                        }
                                    </p>
                                }
                            }
                        }
                    </div>
                </div>
                @if (Session["LogedUserId"] != null)
                {
                    if (Session["UserLevel"].ToString() == "99")
                    {
                    <a href="/Vision/EditVision" class="btn btn-theme">Edit Content</a>
                    }
                }
            </div>
        </section>
        <section id="bottom">
            <div class="container">
                <div class="row">
                    <div class="span12">
                        <div class="aligncenter">
                            <div id="twitter-wrapper">
                                <div id="twitter">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <a href="#" class="scrollup"><i class="icon-chevron-up icon-square icon-32 active"></i></a>

</body>