WebPortal_BAK/WebPortal/Controllers/DataSetting/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPortal.GeneralClass;
using WebPortal.Model;
using WebPortal.Models;

namespace WebPortal.Controllers.DataSetting
{
    [NoDirectAccess]
    [SessionTimeout]
    public class ProjectController : Controller
    {
        //
        // GET: /Project/
        oGeneral ogeneral = new oGeneral();
        FrInternallEntities db = new FrInternallEntities();

        public ActionResult Index(int? Page)
        {
            int startIndex = 0;
            int loadPage = 0;

            if (Page != null)
            {
                loadPage = Page.HasValue ? Page.Value - 1 : 0;
                startIndex = 20 * loadPage;
            }

            List<T_MsProject> listProject = db.T_MsProject.OrderBy(o => o.ProjectName).Skip(startIndex).Take(20).ToList();

            int totalProject = db.T_MsProject.Count();
            int totalPages = (totalProject / 20) + (totalProject % 20 > 0 ? 1 : 0);

            PagingAndGroup mod = new PagingAndGroup();
            mod.listProject = listProject;
            mod.currentPage = loadPage + 1;
            mod.totalItem = totalProject;
            mod.totalPages = totalPages;

            mod = ogeneral.getPaging(mod);

            return View(mod);
        }

        [HttpGet]
        public ActionResult AddProject()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddProject(T_MsProject project)
        {
            if (ModelState.IsValid)
            {
                T_MsProject newProject = new T_MsProject();
                newProject.ProjectCode = project.ProjectCode;
                newProject.ProjectName = project.ProjectName;
                newProject.CreatedBy = Session["LogedUserId"].ToString();
                newProject.CreatedDate = DateTime.Now;

                db.T_MsProject.Add(newProject);
                db.SaveChanges();

                TempData["Message"] = "Project Added";
                return RedirectToAction("Index");
            }

            return View(project);
        }

        [HttpGet]
        public ActionResult EditProject(string projectCode)
        {
            T_MsProject project = db.T_MsProject.Where(w => w.ProjectCode == projectCode).First();

            return View(project);
        }

        [HttpPost]
        public ActionResult EditProject(T_MsProject project)
        {
            if (ModelState.IsValid)
            {
                T_MsProject dbProject = db.T_MsProject.Where(w => w.ProjectCode == project.ProjectCode).First();
                dbProject.ProjectName = project.ProjectName;
                dbProject.ModifyBy = Session["LogedUserId"].ToString();
                dbProject.ModifyDate = DateTime.Now;

                db.SaveChanges();

                TempData["Message"] = "Project Updated";
                return RedirectToAction("Index");
            }

            return View(project);
        }

        public ActionResult DeleteProject(string projectCode)
        {
            T_MsProject dbProject = db.T_MsProject.Where(w => w.ProjectCode == projectCode).First();

            db.T_MsProject.Remove(dbProject);
            db.SaveChanges();

            TempData["Message"] = "Project Deleted";
            return RedirectToAction("Index");
        }
    }
}

WebPortal_BAK/WebPortal/Controllers/DataSetting/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPortal.Model;
using WebPortal.Models;
using PagedList;
using WebPortal.GeneralClass;
using System.Text.RegularExpressions;

namespace WebPortal.Controllers.DataSetting
{
    //[NoDirectAccess]
    [SessionTimeout]
    public class UserController : Controller
    {
        //
        // GET: /User/
        oGeneral ogeneral = new oGeneral();
        FrInternallEntities db = new FrInternallEntities();
        

        public ActionResult Index(int? Page)
        {
            int startIndex = 0;
            int loadPage = 0;

            if (Page != null)
            {
                loadPage = Page.HasValue ? Page.Value - 1 : 0;
                startIndex = 20 * loadPage;
            }

            List<UserWithLevel> listUser = (from user in db.T_MsUser.OrderBy(o => o.UserName).Skip(startIndex).Take(20)
                                           join userLevel in db.T_MsUserGroup on user.UserLevel equals userLevel.UserLevel
                                           select new UserWithLevel
                                           {
                                               UserId = user.UserId,
                                               UserName = user.UserName,
                                               Email = user.email,
                                               UserLevel = user.UserLevel,
                                               Description = userLevel.Description
                                           }).ToList();

            int totalUser = db.T_MsUser.Count();
            int totalPages = (totalUser / 20) + (totalUser % 20 > 0 ? 1 : 0);

            PagingAndGroup mod = new PagingAndGroup();
            mod.listUser = listUser;
            mod.currentPage = loadPage + 1;
            mod.totalItem = totalUser;
            mod.totalPages = totalPages;

            mod = ogeneral.getPaging(mod);

            return View(mod);
        }

        [HttpGet]
        public ActionResult AddUser()
        {
            List<DropdownModel> UserGroupList = (from usergroup in db.T_MsUserGroup
                                                select new DropdownModel
                                                {
                                                    intValue = usergroup.UserLevel,
                                                    Text = usergroup.Description
                                                }).OrderBy(o => o.intValue).ToList();
            ViewBag.UserGroupList = new SelectList(UserGroupList, "intValue", "Text");

            List<DropdownModel> RegionList = new List<DropdownModel>();
            RegionList.Add(new DropdownModel { stringValue = "Jakarta", Text = "Jakarta" });
            RegionList.Add(new DropdownModel { stringValue = "Pekanbaru", Text = "Pekanbaru" });
            RegionList.Add(new DropdownModel { stringValue = "Balikpapan", Text = "Balikpapan" });
            RegionList.Add(new DropdownModel { stringValue = "Pontianak", Text = "Pontianak" });
            RegionList.Add(new DropdownModel { stringValue = "-", Text = "-" });
            ViewBag.RegionList = new SelectList(RegionList, "stringValue", "Text");

            return View();

        }

        [HttpPost]
        public ActionResult AddUser(T_MsUser user)
        {
            bool isTemporary = false;

            if (user.Region == "")
                ModelState.AddModelError("Region", "Please Choose Region"); 

            if (user.Jabatan == "")
                ModelState.AddModelError("Jabatan", "Please Fill User Position");

            if (user.Divisi == "")
                ModelState.AddModelError("Dision", "Please Fill User Division");

            if (user.email == "")
                ModelState.AddModelError("email", "Please Fill User Email");
            //else
            //{
            //    Match match = Regex.Match(user.email, @"^[a-zA-Z0-9_\\+-]+(\\.[a-zA-Z0-9_\\+-]+)*@[a-zA-Z0-9-]+(\\.[a-zA-Z0-9]+)*\\.([a-zA-Z]{2,4})$");

            //    if (!match.Success)
            //        ModelState.AddModelError("email", "Invalid Email Format");
            //}

            if (user.StartAccess != null || user.EndAccess != null)
            {
                if (user.StartAccess == null)
                {
                    ModelState.AddModelError("StartAccess", "Please Choose Start Date"); 
                }
                else if (user.EndAccess == null)
                {
                    ModelState.AddModelError("EndAccess", "Please Choose End Date"); 
                }
                else
                {
                    isTemporary = true;
                }
            }

            if (ModelState.IsValid)
            {
                T_MsUser newUser = new T_MsUser();

                newUser.UserId = user.UserId;
                newUser.UserName = user.UserName;
                newUser.Password = ogeneral.Encrypt(ogeneral.randomString(8));
                newUser.Region = user.Region;
                newUser.email = user.email;
                newUser.Jabatan = user.Jabatan;
                newUser.Divisi = user.Divisi;
                newUser.UserLevel = user.UserLevel;
                newUser.CreatedBy = Session["LogedUserID"].ToString();
                newUser.CreatedDate = DateTime.Now;
                newUser.Image = "/Design/assets/People/man.jpg";
                newUser.IsTemporary = isTemporary;

                if (isTemporary)
                {
                    newUser.StartAccess = user.StartAccess;
                    newUser.EndAccess = user.EndAccess;
                }

                db.T_MsUser.Add(newUser);
                db.SaveChanges();

                TempData["Message"] = "User Added";
                return RedirectToAction("Index");
            }

            List<DropdownModel> UserGroupList = (from usergroup in db.T_MsUserGroup
                                                 select new DropdownModel
                                                 {
                                                     intValue = usergroup.UserLevel,
                                                     Text = usergroup.Description
                                                 }).OrderBy(o => o.intValue).ToList();
            ViewBag.UserGroupList = new SelectList(UserGroupList, "intValue", "Text");

            List<DropdownModel> RegionList = new List<DropdownModel>();
            RegionList.Add(new DropdownModel { stringValue = "Jakarta", Text = "Jakarta" });
            RegionList.Add(new DropdownModel { stringValue = "Pekanbaru", Text = "Pekanbaru" });
            RegionList.Add(new DropdownModel { stringValue = "Balikpapan", Text = "Balikpapan" });
            RegionList.Add(new DropdownModel { stringValue = "Pontianak", Text = "Pontianak" });
            RegionList.Add(new DropdownModel { stringValue = "-", Text = "-" });
            ViewBag.RegionList = new SelectList(RegionList, "stringValue", "Text");

            return View(user);
        }

        [HttpGet]
        public ActionResult EditUser(string userId)
        {
            T_MsUser user = db.T_MsUser.Where(w => w.UserId == userId).FirstOrDefault();

            List<DropdownModel> UserGroupList = (from usergroup in db.T_MsUserGroup
                                                 select new DropdownModel
                                                 {
                                                     intValue = usergroup.UserLevel,
                                                     Text = usergroup.Description
                                                 }).OrderBy(o => o.intValue).ToList();
            ViewBag.UserGroupList = new SelectList(UserGroupList, "intValue", "Text");

            List<DropdownModel> RegionList = new List<DropdownModel>();
            RegionList.Add(new DropdownModel { stringValue = "Jakarta", Text = "Jakarta" });
            RegionList.Add(new DropdownModel { stringValue = "Pekanbaru", Text = "Pekanbaru" });
            RegionList.Add(new DropdownModel { stringValue = "Balikpapan", Text = "Balikpapan" });
            RegionList.Add(new DropdownModel { stringValue = "Pontianak", Text = "Pontianak" });
            RegionList.Add(new DropdownModel { stringValue = "-", Text = "-" });
            ViewBag.RegionList = new SelectList(RegionList, "stringValue", "Text");

            return View(user);
        }

        [HttpPost]
        public ActionResult EditUser(T_MsUser user)
        {
            bool isTemporary = false;

            if (user.Region == "")
                ModelState.AddModelError("Region", "Please Choose Region");

            if (user.Jabatan == "")
                ModelState.AddModelError("Jabatan", "Please Fill User Position");

            if (user.Divisi == "")
                ModelState.AddModelError("Dision", "Please Fill User Division");

            if (user.email == "")
                ModelState.AddModelError("email", "Please Fill User Email");

            if (user.StartAccess != null || user.EndAccess != null)
            {
                if (user.StartAccess == null)
                {
                    ModelState.AddModelError("StartAccess", "Please Choose Start Date"); 
                }
                else if (user.EndAccess == null)
                {
                    ModelState.AddModelError("EndAccess", "Please Choose End Date"); 
                }
                else
                {
                    isTemporary = true;
                }
            }

            if (ModelState.IsValid)
            {
                var dbUser = db.T_MsUser.Where(a => a.UserId.Equals(user.UserId)).FirstOrDefault();

                dbUser.UserName = user.UserName;
                dbUser.Region = user.Region;
                dbUser.email = user.email;
                dbUser.Jabatan = user.Jabatan;
                dbUser.Divisi = user.Divisi;

WebPortal_BAK/WebPortal/Views/DataSetting/Project/AddProject.cshtml
@model WebPortal.Model.T_MsProject
@{
    ViewBag.Title = "Web Portal | Add New Project";
}


<div id="wrapper">
    <section id="inner-headline">
        <div class="container">
            <div class="row">
                <div class="span4">
                    <div class="inner-heading">
                        <h2>Add New Project</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="content">
        <div class="container">
            <div class="row">
                <div class="span4">
                    <a href="/User/Index" class="btn btn-purple" onclick="return confirm('Are you wish to discard this project?');"><i class="icon-chevron-left"></i>Back</a>
                </div>
            </div>
            <div class="row">
                <div class="span12">
                    @using (Html.BeginForm("AddProject", "Project", FormMethod.Post, new { @class = "contactForm", @enctype = "multipart/form-data" }))
                    {
                        <div class="row">
                            <div class="span2 form-group">
                                <h6>Project Code : </h6>
                            </div>
                            <div class="span4 form-group">
                                @Html.TextBoxFor(model => model.ProjectCode, new { @id = "ProjectCode", @class = "form-control", @placeholder = "*Project Code" })
                                @Html.ValidationMessageFor(model => model.ProjectCode, "", new { @style = "color: #a94442;" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="span2 form-group">
                                <h6>Project Name : </h6>
                            </div>
                            <div class="span4 form-group">
                                @Html.TextBoxFor(model => model.ProjectName, new { @id = "ProjectName", @class = "form-control", @placeholder = "*Project Name" })
                                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @style = "color: #a94442;" })
                            </div>
                        </div>
                        <div class="row">
                            <p class="text-center">
                                <button class="btn btn-large btn-theme margintop10" type="submit">Create Project</button>
                            </p>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
    <section id="bottom">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="aligncenter">
                        <div id="twitter-wrapper">
                            <div id="twitter">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

WebPortal_BAK/WebPortal/Views/DataSetting/Project/EditProject.cshtml
@model WebPortal.Model.T_MsProject
@{
    ViewBag.Title = "Web Portal | Edit Project";
}


<div id="wrapper">
    <section id="inner-headline">
        <div class="container">
            <div class="row">
                <div class="span4">
                    <div class="inner-heading">
                        <h2>Edit Project</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="content">
        <div class="container">
            <div class="row">
                <div class="span4">
                    <a href="/User/Index" class="btn btn-purple" onclick="return confirm('Are you wish to discard this changes?');"><i class="icon-chevron-left"></i>Back</a>
                </div>
            </div>
            <div class="row">
                <div class="span12">
                    @using (Html.BeginForm("EditProject", "Project", FormMethod.Post, new { @class = "contactForm", @enctype = "multipart/form-data" }))
                    {
                        <div class="row">
                            <div class="span2 form-group">
                                <h6>Project Code : </h6>
                            </div>
                            <div class="span4 form-group">
                                @Html.TextBoxFor(model => model.ProjectCode, new { @id = "ProjectCode", @class = "form-control", @placeholder = "*Project Code", @readonly = "readonly" })
                                @Html.ValidationMessageFor(model => model.ProjectCode, "", new { @style = "color: #a94442;" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="span2 form-group">
                                <h6>Project Name : </h6>
                            </div>
                            <div class="span4 form-group">
                                @Html.TextBoxFor(model => model.ProjectName, new { @id = "ProjectName", @class = "form-control", @placeholder = "*Project Name" })
                                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @style = "color: #a94442;" })
                            </div>
                        </div>
                        <div class="row">
                            <p class="text-center">
                                <button class="btn btn-large btn-theme margintop10" type="submit">Edit Project</button>
                            </p>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
    <section id="bottom">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="aligncenter">
                        <div id="twitter-wrapper">
                            <div id="twitter">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

WebPortal_BAK/WebPortal/Views/DataSetting/Project/Index.cshtml
@model WebPortal.Models.PagingAndGroup
@{
    ViewBag.Title = "Web Portal | Project List";
}
@{
    int num = 1;
}

<div id="wrapper">
    <section id="inner-headline">
        <div class="container">
            <div class="row">
                <div class="span4">
                    <div class="inner-heading">
                        <h2>Project List</h2>
                    </div>
                </div>

            </div>
        </div>
    </section>
    <section id="content">
        <div class="container">
            <div class="row">
                <div class="span4">
                    <a href="/Project/AddProject" class="btn btn-theme">Add New Project</a>
                </div>

            </div>
            <div class="row">
                <div class="span12">
                    <table class="table table-striped" id="UserTable">
                        <thead>
                            <tr>
                                <th>No.
                                </th>
                                <th>Project Code
                                </th>
                                <th>Project Name
                                </th>
                                <th>Action
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.listProject)
                            {
                                <tr>
                                    <td style="width: 5%">@num
                                    </td>
                                    <td style="width: 25%">@Html.DisplayFor(modelItem => item.ProjectCode)
                                    </td>
                                    <td style="width: 45%">@Html.DisplayFor(modelItem => item.ProjectName)
                                    </td>
                                    <td style="width: 15%"><a href="/Project/EditProject/?projectCode=@item.ProjectCode" class="btn btn-green"><i class="icon-edit"></i></a>&nbsp<a href="/Project/DeleteProject/?projectCode=@item.ProjectCode" class="btn btn-red" onclick = "return confirm('Are you wish to delete this project?');"><i class="icon-trash"></i></a>
                                    </td>
                                </tr>    
                                { num++; }                              
                            }
                        </tbody>
                    </table>

                    <div id="pagination">
                        @if (Model.toFirst)
                        {
                            <a href="/User/Index/?Page=1" class="inactive"><<</a>
                        }

                        @for (int i = Model.startPage; i <= Model.endPage; i++)
                        {
                            if (i == Model.currentPage)
                            {
                            <span class="current">@i</span>
                            }
                            else
                            {
                            <a href="/User/Index/?Page=@i" class="inactive">@i</a>
                            }
                        }

                        @if (Model.toLast)
                        {
                            <a href="/User/Index/?Page=@Model.totalPages" class="inactive">>></a>
                        }
                    </div>

                </div>
            </div>

        </div>
    </section>
    <section id="bottom">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="aligncenter">
                        <div id="twitter-wrapper">
                            <div id="twitter">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        var tempMessage = '@TempData["Message"]';

        if (tempMessage != '') {
            $.notify({
                // options
                message: tempMessage
            }, {
                // settings
                type: 'success'
            });
        }
    });

</script>